### PR TITLE
WIP: Ginga viewer for ASDF

### PR DESCRIPTION
**Pull request by pllim**
An alternate approach to spacetelescope/stginga#157 . Depends on spacetelescope/gwcs#146 and ejeschke/ginga#327 .

c/c @hcferguson

### CODE REVIEW

**Comment by pllim** [comment]
@sosey , I believe `imexam` uses similar Ginga backend? We can certainly join forces where it makes sense to do so!

**Comment by sosey** [comment]
@pllim should we go ahead and merge this?

**Comment by pllim** [comment]
I don't remember what this was for now... And "from unknown repository" looks sketchy. Did I delete my fork?!

**Comment by pllim** [comment]
Also ejeschke/ginga#327 is still not merged yet, so I don't think this can be merged regardless.

**Comment by sosey** [comment]
I'm gunna close this then....you can open another one if it becomes relevant

**Pull request closed without merging**
